name: airportshuttle4less
description: "Flutter Android and iOS Mobile App for Airport Shuttle Service"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Date & Time
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  # State management, DI, Routing
  get: ^4.6.6

  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.1

  # Storage & Config
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1

  # Logging
  logger: ^2.5.0

  # Icons
  iconsax: ^0.0.8

  # UI
  persistent_bottom_nav_bar_v2: ^6.2.0
  url_launcher: ^6.3.2
  lottie: ^3.3.2

  # Image & Location
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lotties/
    - assets/images/
    - assets/images/common/
    - assets/images/common/empty/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/app_icon.png"
